### ISSUE TITLE
Bad components

### ISSUE THREAD

**Issue by atsuch** [guruucsd/lateralized-components#30]
I was working with 20 components, and found that there a few (1 for R, another for L) components with a very few voxels with extreme values, resulting in the overall dark image. This one example has the max value of 0.43, when other images have max values around 0.02. Any idea why we get this, @bcipolli ??
![wb_r_6](https://cloud.githubusercontent.com/assets/9255297/13785412/d938b422-eaa9-11e5-9a9d-58ae0073be07.png)

**Comment by bcipolli** [comment]
Never seen it, but glad to take a look tomorrow morning!

**Comment by atsuch** [comment]
Hmm... in our code, plotting components individually (no comparison between components) when doing ICA for the first time didn't have the colorbar. So I tried adding the colorbar and reran ICA with --force and n-components =5, and got similarly bad components (one each for R, L, and wb: see below
). I might have to rerun QC to see if any new images are corrupting the analysis..

![l_component_1](https://cloud.githubusercontent.com/assets/9255297/13788874/06a785c4-eab8-11e5-9ab8-7357bcc3536d.png)
![r_component_4](https://cloud.githubusercontent.com/assets/9255297/13788882/0e1aaa5c-eab8-11e5-82f4-8a6f948bb72d.png)
![wb_component_3](https://cloud.githubusercontent.com/assets/9255297/13788889/18f284fe-eab8-11e5-831f-77ecb06c7ca5.png)

**Comment by atsuch** [comment]
@bcipolli, do you see this type of components if you rerun the ICA? Could you help me troubleshoot?

**Comment by bcipolli** [comment]
I see the first image that you show. I see that the scale bars are strangely high.

**Comment by bcipolli** [comment]
@atsuch I didn't see any bad components in n=5 as you did. I saw one with an improper scalebar, but looks like it would be OK if rescaled.

**Comment by bcipolli** [comment]
@atsuch have you seen this since then? I have not... perhaps our qc.py improved enough that these went away?

**Comment by bcipolli** [comment]
This was fixed along the way; closing.
