### ISSUE TITLE
python crash when running ps.py

### ISSUE THREAD

**Issue by atsuch** [guruucsd/lateralized-components#31]
At least on my machine, I haven't been able to test my new ps.py since my python always crash before completing all the component number and matching methods. @bcipolli, any idea why this might be the case?

I'm wondering if running get_dataset for every iteration of main.py is at least part of the problem? If that's the case, I'm thinking of adding the option to pass the images and term_scores to main.py rather than always running it inside main.py. What do you think?

**Comment by bcipolli** [comment]
>running get_dataset for every iteration of main.py is at least part of the problem?

This is definitely slow.

>I'm thinking of adding the option to pass the images and term_scores to main.py rather than always running it inside main.py. What do you think?

👍 :)

> I haven't been able to test my new ps.py since my python always crash before completing all the component number and matching methods

I will try fetching this now & running. `main.py` and `ps.py` are both hella-slow for me ...

**Comment by bcipolli** [comment]
@atsuch are you still having this issue?

**Comment by bcipolli** [comment]
I have seen that, in some cases, if a valid exception is thrown, this will crash Python under low memory situations.

I have run `ps.py` now; it was broken by some renaming changes, so fixed that up. I'll assume that anything else has been fixed.
