### ISSUE TITLE
RuntimeWarning error when getting dataset

### ISSUE THREAD

**Issue by atsuch** [guruucsd/lateralized-components#60]
I was testing my code, and encountered the following;

  File "main.py", line 365, in <module>
    components=components, query_server=query_server, plot=plot, **args)
  File "main.py", line 254, in loop_main_and_plot
    query_server=query_server)
  File "main.py", line 60, in get_dataset
    images, term_scores = fetch_neurovault(max_images=max_images, **kwargs)
  File "/home/ami/Documents/Work/imaging/RL_ICA/OHBM-2016/nilearn_ext/datasets.py", line 174, in fetch_neurovault
    images, term_scores = _neurovault_remove_bad_images(images, term_scores)
  File "/home/ami/Documents/Work/imaging/RL_ICA/OHBM-2016/nilearn_ext/datasets.py", line 98, in _neurovault_remove_bad_images
    is_rejected = np.all(dat > 0) or np.all(dat < 0) or (np.unique(dat).size < 2000)
RuntimeWarning: invalid value encountered in greater

Since I have ICA images, I don't really need to get new images unless I want to re-calculate ICA images with newer dataset, but currently we get dataset regardless. Maybe we should change that... :P But anyhow, dataset.py needs a fix, it seems..

**Comment by bcipolli** [comment]
Try running with `--offline`. Looks to me like one of the newer images has an unexpected data type in it. I haven't been able to replicate..

**Comment by bcipolli** [comment]
Ah, I had to upgrade my libraries (probably numpy), and was able to replicate. Debugging now.

**Comment by bcipolli** [comment]
Fixed in aac9af0
